from database.database import db
from datetime import datetime

class QuizSet(db.Model):
    """User-created quiz/exam sets generated by Hanachan"""
    __tablename__ = 'quiz_sets'
    
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=True)
    creator_id = db.Column(db.String(120), nullable=True)  # User who created it
    
    # Quiz metadata
    quiz_type = db.Column(db.String(50), default='quiz')  # quiz, exam, practice
    level = db.Column(db.String(10), nullable=True)  # N5, N4, N3, N2, N1
    skill = db.Column(db.String(50), nullable=True)  # vocabulary, grammar, reading, listening
    time_limit_minutes = db.Column(db.Integer, nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Ownership flags
    is_public = db.Column(db.Boolean, default=False)
    is_saved = db.Column(db.Boolean, default=False)  # Whether user saved to library
    
    # Relationship to questions
    questions = db.relationship('QuizQuestion', backref='quiz_set', cascade="all, delete-orphan")

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'creatorId': self.creator_id,
            'quizType': self.quiz_type,
            'level': self.level,
            'skill': self.skill,
            'timeLimitMinutes': self.time_limit_minutes,
            'questionCount': len(self.questions),
            'questions': [q.to_dict() for q in self.questions],
            'createdAt': self.created_at.isoformat() if self.created_at else None,
            'isPublic': self.is_public,
            'isSaved': self.is_saved
        }


class QuizQuestion(db.Model):
    """Individual question within a quiz"""
    __tablename__ = 'quiz_questions'
    
    id = db.Column(db.Integer, primary_key=True)
    set_id = db.Column(db.Integer, db.ForeignKey('quiz_sets.id'), nullable=False)
    
    # Question content
    question_type = db.Column(db.String(50), default='multiple_choice')  # multiple_choice, true_false, fill_blank
    content = db.Column(db.Text, nullable=False)  # The question text
    passage = db.Column(db.Text, nullable=True)  # For reading questions
    audio_url = db.Column(db.String(512), nullable=True)  # For listening questions
    
    # Correct answer
    correct_answer = db.Column(db.String(255), nullable=False)  # Can be option ID or text
    explanation = db.Column(db.Text, nullable=True)
    
    # Metadata
    skill = db.Column(db.String(50), nullable=True)
    difficulty = db.Column(db.Integer, default=3)  # 1-5
    order_index = db.Column(db.Integer, default=0)
    
    # Relationship to options
    options = db.relationship('QuizOption', backref='question', cascade="all, delete-orphan")

    def to_dict(self):
        return {
            'id': self.id,
            'type': self.question_type,
            'content': self.content,
            'passage': self.passage,
            'audioUrl': self.audio_url,
            'options': [o.to_dict() for o in self.options],
            'correctAnswer': self.correct_answer,
            'explanation': self.explanation,
            'skill': self.skill,
            'difficulty': self.difficulty
        }


class QuizOption(db.Model):
    """Options for a multiple choice question"""
    __tablename__ = 'quiz_options'
    
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('quiz_questions.id'), nullable=False)
    
    option_id = db.Column(db.String(10), nullable=False)  # a, b, c, d
    text = db.Column(db.Text, nullable=False)
    order_index = db.Column(db.Integer, default=0)

    def to_dict(self):
        return {
            'id': self.option_id,
            'text': self.text
        }
