from pydantic import BaseModel, Field
from typing import List, Optional, Any, Dict

class ResourceDTO(BaseModel):
    id: Optional[int] = None
    title: str
    type: str # 'document', 'image', 'url'
    content: Optional[str] = None

class ContextConfigurationDTO(BaseModel):
    model_name: Optional[str] = 'gpt-4o'
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = 1000
    resource_ids: Optional[List[int]] = []

class ChatMessageDTO(BaseModel):
    id: Optional[int] = None
    role: str
    content: str
    created_at: Optional[str] = None
    attachments: Optional[List[ResourceDTO]] = []
    # Content generated by the system
    artifacts: Optional[List[Dict[str, Any]]] = [] # List of ArtifactDTO (dict for now to avoid circular dependency issues if any, or just use ArtifactDTO forward ref)
    tasks: Optional[List[Dict[str, Any]]] = []
    suggestions: Optional[List[Dict[str, Any]]] = []

class AgentRequest(BaseModel):
    session_id: str
    user_id: str
    prompt: str
    context_config: Optional[ContextConfigurationDTO] = None
    history: Optional[List[ChatMessageDTO]] = []

class ArtifactContent(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    key_points: Optional[List[str]] = []
    # Flexible field for different types (FlashcardSet dict, Mindmap dict)
    # matching response.json "content" structure
    flashcards: Optional[Dict[str, Any]] = None 
    mindmap: Optional[Dict[str, Any]] = None
    audio: Optional[List[Dict[str, str]]] = [] # List of {text, url}
    vocabulary: Optional[Dict[str, Any]] = None
    task: Optional[Dict[str, Any]] = None
    quiz: Optional[Dict[str, Any]] = None  # Quiz/Exam artifact

class ResponseItemDTO(BaseModel):
    responseId: Optional[str] = None
    type: str # 'flashcard', 'mindmap', 'audio'
    content: Any # Can be ArtifactContent or plain text string
    citations: Optional[List[Dict[str, str]]] = []

class AgentResponse(BaseModel):
    sessionId: str
    userId: str
    status: str = "completed"
    # The JSON shows 'responses' as the list of artifacts/content
    responses: List[ResponseItemDTO] = [] 
    proposedTasks: List[Dict[str, Any]] = []
    suggestions: List[Dict[str, Any]] = []

